version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: studentinfo-backend
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Server=tcp:qa-server-testproject.database.windows.net,1433;Initial Catalog=QA-test;Persist Security Info=False;User ID=admin123;Password=Jayaru123;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;
    restart: on-failure

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: studentinfo-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: on-failure
